name: Docker Image CI

on:
  workflow_run:
    workflows: ["Tests"]
    types: completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd backend && docker build . --file Dockerfile --tag my-image-name:$(date +%s)

